services:

    Instride\Bundle\OpenDxpCampaignsBundle\Command\SyncNewsletterCommand:
        arguments:
            $registry: '@Instride\Bundle\OpenDxpCampaignsBundle\Driver\DriverRegistry'
            $newsletterManager: '@Instride\Bundle\OpenDxpCampaignsBundle\Newsletter\NewsletterManagerInterface'
            $bus: '@Symfony\Component\Messenger\MessageBusInterface'
            # MemberResolverInterface and MemberProviderInterface are optional
            $memberResolver: '@?Instride\Bundle\OpenDxpCampaignsBundle\DataObject\MemberResolverInterface'
            $memberProvider: '@?Instride\Bundle\OpenDxpCampaignsBundle\DataObject\MemberProviderInterface'
        tags:
            - { name: console.command }
