services:

    Instride\Bundle\OpenDxpCampaignsBundle\Controller\Webhook\MailchimpWebhookController:
        arguments:
            $registry: '@Instride\Bundle\OpenDxpCampaignsBundle\Driver\DriverRegistry'
            $memberResolver: '@Instride\Bundle\OpenDxpCampaignsBundle\DataObject\MemberResolverInterface'
            $mapper: '@Instride\Bundle\OpenDxpCampaignsBundle\Newsletter\MergeFieldMapper'
            $eventDispatcher: '@Symfony\Contracts\EventDispatcher\EventDispatcherInterface'
            $logger: '@logger'
        tags:
            - { name: controller.service_arguments }
        public: true
